#!/usr/bin/env python3
"""Refresh data/routes.js from the BCN Riders club on Ride with GPS.

Usage:  python3 scripts/update_routes.py
Writes a small JS file (window.BCN_ROUTES = [...]) so the site works as plain
static files, including when opened straight from disk.
"""
import json
import pathlib
import re
import urllib.request

CLUB_ID = 8423
URL = f"https://ridewithgps.com/clubs/{CLUB_ID}/routes.json?limit=500"
OUT = pathlib.Path(__file__).resolve().parent.parent / "data" / "routes.js"

# Routes shown as full Ride with GPS map embeds at the top of the Routes section.
FEATURED = [51156160, 51156224, 48302922, 48302809]


def classify(r):
    name = r["name"].lower()
    unpaved = r.get("unpaved_pct") or 0
    if "hike" in name:
        return "other"
    if "mtb" in name:
        return "mtb"
    if re.search(r"\broad\b", name):
        return "road"
    if "grvl" in name or "gravel" in name or "traka" in name or unpaved >= 30:
        return "gravel"
    return "road" if unpaved < 15 else "gravel"


def main():
    req = urllib.request.Request(URL, headers={"User-Agent": "bcn-riders-site"})
    with urllib.request.urlopen(req) as resp:
        data = json.load(resp)

    routes = []
    for r in data["results"]:
        if r.get("visibility") != 0 or r.get("deleted_at") or r.get("archived_at"):
            continue  # public, live routes only
        routes.append({
            "id": r["id"],
            "name": r["name"].strip(),
            "km": round(r["distance"] / 1000, 1),
            "gain": round(r.get("elevation_gain") or 0),
            "unpaved": max(r.get("unpaved_pct") or 0, 0),
            "start": (r.get("locality") or "").strip(),
            "type": "loop" if r.get("track_type") == "loop" else "point to point",
            "kind": classify(r),
            "created": r["created_at"][:10],
            "featured": r["id"] in FEATURED,
        })
    routes.sort(key=lambda x: x["created"], reverse=True)

    OUT.write_text(
        "// Generated by scripts/update_routes.py. Do not edit by hand.\n"
        f"window.BCN_CLUB_ID = {CLUB_ID};\n"
        f"window.BCN_FEATURED = {json.dumps(FEATURED)};\n"
        "window.BCN_ROUTES = " + json.dumps(routes, ensure_ascii=False, indent=1) + ";\n"
    )
    print(f"Wrote {len(routes)} routes to {OUT}")


if __name__ == "__main__":
    main()
